### ISSUE TITLE
SiriGPT Request Error

### ISSUE THREAD

**Issue by PixelScribe55** [nicolodiamante/SiriGPT#10]
Followed set up as closely as I could but Chatty dialogue box comes up saying “You exceeded your current quota, please check your plan and billing details.” I stuck with GPT3.5 as recommended and didn’t alter any of the other parameters. 
Anyone make sense of that?

![IMG_1572](https://github.com/nicolodiamante/SiriGPT/assets/136143628/f0d87884-0aef-488c-96ba-0993bc261ba4)

**Comment by nicolodiamante** [comment]
Hi,
I presume you are using a free plan. This error message indicates that you have hit your maximum monthly spend (hard limit) for the API. This means that you have consumed all the credits or units allocated to your plan and have reached the limit of your billing cycle ($5.00). 
 
To resolve this error, you can follow these steps:
 
- You can see your current usage [here](https://beta.openai.com/account/usage).
- If you are using a free plan, consider upgrading to a pay-as-you-go plan that offers a higher quota.
-  Check your current quota in your account settings [here](https://beta.openai.com/account/billing/limits). If you need a quota increase, you can apply for one [here](https://beta.openai.com/forms/quota-increase).

**Comment by PixelScribe55** [comment]
> Hi, I presume you are using a free plan. This error message indicates that you have hit your maximum monthly spend (hard limit) for the API. This means that you have consumed all the credits or units allocated to your plan and have reached the limit of your billing cycle ($5.00).
> 
> To resolve this error, you can follow these steps:
> 
> * You can see your current usage [here](https://beta.openai.com/account/usage).
> * If you are using a free plan, consider upgrading to a pay-as-you-go plan that offers a higher quota.
> * Check your current quota in your account settings [here](https://beta.openai.com/account/billing/limits). If you need a quota increase, you can apply for one [here](https://beta.openai.com/forms/quota-increase).

Hey, 
No I’ve got a pay as you go profile. My usage also shows as zero, so I’m stumped. 
![IMG_1575](https://github.com/nicolodiamante/SiriGPT/assets/136143628/b7f3b0ea-e722-41c1-a6af-587d97791bae)

**Comment by nicolodiamante** [comment]
I am puzzled too. Have you tried your API with another service by any chance? To determine if it's something with your API or the shortcut itself.

**Comment by PixelScribe55** [comment]
Had someone at OpenAI take a look and it now works perfectly 😁
