### ISSUE TITLE
Receiving Request Error of exceeding current quota.

### ISSUE THREAD

**Issue by davidwu503** [nicolodiamante/SiriGPT#12]
Hello and hope you are well.

I just got a new API for my wife on a new OpenAI account. Then I Installed Chatty exactly as I did for my own chatty on her iPhone and her very first question and every question after returns this error message.

When I log into her Open AI account, the plan says she’s on free plan now so she should have $5 in her plan.

On the official ChatGPT, it does work. Strange…

Any idea why this is happening to her but not to me?

By the way, my personal Chatty works great! Thanks.

![IMG_1960](https://github.com/nicolodiamante/SiriGPT/assets/53504033/55bfe385-324a-42b2-b710-043ccabe7d08)

**Comment by nicolodiamante** [comment]
Thank you for using Chatty! I'm puzzled too that you're seeing an error about "exceeded quota". Since your account is new, it should have the $5 available. Have you tried generating a new API Key to see if that helps?

**Comment by davidwu503** [comment]
Hello Nicolo,

Thanks for your quick reply. Yes I created a new email, got new API from OpenAI on my wife’s phone.

If by mistake, I set up Chatty on her phone  It i stead of using her new API, I used mine instead turn the light off, would OpenAI recognise that her phone had tried to register before and didn’t allow same API on two iPhones and now it knows it’s her phone even with new API?

David

On 25 Jun 2023, at 7:20 PM, Nicolò Diamante ***@***.***> wrote:

﻿

Thank you for using Chatty! I'm puzzled too that you're seeing an error about "exceeded quota". Since your account is new, it should have the $5 available. Have you tried generating a new API Key to see if that helps?

**Comment by nicolodiamante** [comment]
Based on what you've told me, it sounds like your wife's device won't run the shortcut, even though she has her account.

Let's see if we can sort out this situation:

1. First, make sure your wife's OpenAI API key is correctly associated with her device. If you're using DataJar, open it and check that the key stored in the correct path is the correct one.

2. If the key is correct, then let's check if the issue is with the shortcut or your wife's Account/API key. Since you told me your shortcut works, log into your OpenAI account and create a new API key [here](https://beta.openai.com/account/api-keys). Replace your wife's key with your new one and check if the shortcut works. If it does, it could mean that there's an error associated with her OpenAI API, in which case you should reach out to OpenAI.

3. If the shortcut still doesn't work, have your wife create a new API key in her OpenAI account and delete and reinstall the shortcut, using the new API.

If this doesn't solve the problem, please let me know.

**Comment by davidwu503** [comment]
Thank you very much, Nicolò.

Will try it out today.

Best wishes,

David

On 28 Jun 2023, at 12:01 AM, Nicolò Diamante ***@***.***> wrote:

﻿

Based on what you've told me, it sounds like your wife's device won't run the shortcut, even though she has her account.

Let's see if we can sort out this situation:

  1.  First, make sure your wife's OpenAI API key is correctly associated with her device. If you're using DataJar, open it and check that the key stored in the correct path is the correct one.

  2.  If the key is correct, then let's check if the issue is with the shortcut or your wife's Account/API key. Since you told me your shortcut works, log into your OpenAI account and create a new API key here<https://beta.openai.com/account/api-keys>. Replace your wife's key with your new one and check if the shortcut works. If it does, it could mean that there's an error associated with her OpenAI API, in which case you should reach out to OpenAI.

  3.  If the shortcut still doesn't work, have your wife create a new API key in her OpenAI account and delete and reinstall the shortcut, using the new API.

If this doesn't solve the problem, please let me know.

**Comment by davidwu503** [comment]
Oh and I presume I must do all this on her phone right?

On 29 Jun 2023, at 9:26 AM, David Wu ***@***.***> wrote:

﻿
Thank you very much, Nicolò.

Will try it out today.

Best wishes,

David

On 28 Jun 2023, at 12:01 AM, Nicolò Diamante ***@***.***> wrote:

﻿

Based on what you've told me, it sounds like your wife's device won't run the shortcut, even though she has her account.

Let's see if we can sort out this situation:

  1.  First, make sure your wife's OpenAI API key is correctly associated with her device. If you're using DataJar, open it and check that the key stored in the correct path is the correct one.

  2.  If the key is correct, then let's check if the issue is with the shortcut or your wife's Account/API key. Since you told me your shortcut works, log into your OpenAI account and create a new API key here<https://beta.openai.com/account/api-keys>. Replace your wife's key with your new one and check if the shortcut works. If it does, it could mean that there's an error associated with her OpenAI API, in which case you should reach out to OpenAI.

  3.  If the shortcut still doesn't work, have your wife create a new API key in her OpenAI account and delete and reinstall the shortcut, using the new API.

If this doesn't solve the problem, please let me know.

**Comment by nicolodiamante** [comment]
Yes, try on her phone.

**Comment by davidwu503** [comment]
Dear Nocolö,

Thank you Thank you!!

I followed your instructions and now its works like magic on her phone.

May I ask if I can switch the language to Chinese (Cantonese) which is the zh-HK identifier, and is one of the languages already in the Apple iOS software? I noticed that in your code, you did include zh-CN but this is traditional Chinese which is different to Cantonese Chinese (zh-HK)

If I cannot select the iOS language Chinese (Cantonese) zh-HK, then what would I type it in the First Language Request during set up?

With many many regards,

	
David Wu
***@***.***
(Not on social media anymore)

**Comment by davidwu503** [comment]
Dear Nocolö,

Sorry for not thinking of this a when I sent my email below. Instead of upgrading my Chatty Version 1.3, instead can I create new API and install Chatty version 1.35 as a separate shortcut alongside the 1.3 version? (I’ll change the name of course)

Or should I just upgrade to 1.35?

All the best,

David

On 1 Jul 2023, at 1:37 PM, David Wu ***@***.***> wrote:

﻿ Dear Nocolö,

Thank you Thank you!!

I followed your instructions and now its works like magic on her phone.

May I ask if I can switch the language to Chinese (Cantonese) which is the zh-HK identifier, and is one of the languages already in the Apple iOS software? I noticed that in your code, you did include zh-CN but this is traditional Chinese which is different to Cantonese Chinese (zh-HK)

If I cannot select the iOS language Chinese (Cantonese) zh-HK, then what would I type it in the First Language Request during set up?

With many many regards,

[https://img.mysignature.io/p/c/a/4/ca436491-55b6-54e7-a0ec-fb87a089e0f9.png?time=1600347888]
David Wu
***@***.***
(Not on social media anymore)




On 28 Jun 2023, at 12:01 AM, Nicolò Diamante ***@***.***> wrote:



Based on what you've told me, it sounds like your wife's device won't run the shortcut, even though she has her account.

Let's see if we can sort out this situation:

  1.  First, make sure your wife's OpenAI API key is correctly associated with her device. If you're using DataJar, open it and check that the key stored in the correct path is the correct one.

  2.  If the key is correct, then let's check if the issue is with the shortcut or your wife's Account/API key. Since you told me your shortcut works, log into your OpenAI account and create a new API key here<https://beta.openai.com/account/api-keys>. Replace your wife's key with your new one and check if the shortcut works. If it does, it could mean that there's an error associated with her OpenAI API, in which case you should reach out to OpenAI.

  3.  If the shortcut still doesn't work, have your wife create a new API key in her OpenAI account and delete and reinstall the shortcut, using the new API.

If this doesn't solve the problem, please let me know.

**Comment by nicolodiamante** [comment]
Hi, David

I'm happy to hear that your wife's shortcut is finally working! As I'm planning to add Cantonese Chinese in the next minor update, I hope you stay patient for now. You can both keep versions 1.3 and 1.3.5, if you don't encounter any issues then you can keep just 1.3.5.

Thanks,
Nico
