### ISSUE TITLE
Doesn't read response aloud

### ISSUE THREAD

**Issue by haydenthai** [nicolodiamante/SiriGPT#3]
So, the shortcut works properly and shows the ChatGPT response from the completion endpoint but doesn't read it aloud.

**Comment by nicolodiamante** [comment]
To have the output read aloud to you, you need to launch the shortcut via Siri by saying "Hey Siri," followed by the name you have given the shortcut. Once you ask your question, Siri will provide the answer audibly.

**Comment by haydenthai** [comment]
Right, when I say "hey siri,explain me ..." Siri should read aloud the response but instead it just leaves the paragraph on my screen. On your end, does it read it aloud? Btw, I'm running IOS 16.3.1 on IPhone 13

**Comment by agold2012** [comment]
Same here. It reads the response when I activate it by tapping the shortcut in "shortcuts," but when I activate it any other way, it only displays the text on the screen. Maybe this is an iphone setting?

**Comment by agold2012** [comment]
I was able to solve the problem by adjusting settings on my phone - Siri & Search > Siri Responses > Automatic.

**Comment by haydenthai** [comment]
Thank you! I had it set to prefers silent which caused this issue!

![image](https://user-images.githubusercontent.com/3473133/236853320-b9f6eed0-39e1-43ee-8274-5889b4fa5c39.png)
