### ISSUE TITLE
Shortcut wants to share calendar events for every request

### ISSUE THREAD

**Issue by verisgit** [nicolodiamante/SiriGPT#6]
It seems every request is trying to send 1 location, 43-48 calendar events and 1 text item to api.openai.com.

I don't want to send my calendar events to openai, if I disable them in permissions, then the shortcut won't run and reports "the shortcut can't access api.openai.com".

Why's it sending them in the first place, and how do I disable that functionality? 

Thanks for the help.

**Comment by rcampbel3** [comment]
I have the same question/concern

**Comment by nicolodiamante** [comment]
Hey everyone, the shortcut is asking for access to the calendar in order to give users an organized summary of their daily schedules, if asked. The location is requested to tailor the format of the date and metric base on the user's country.

I find it strange that the shortcut won't function unless it has access to the calendar, since it's unrelated to the intended purpose of the script. Further, it should not interfere with the API or prevent it from responding, I'll take a look into it.

If having access to the calendar creates any concern, I can remove the option, just let me know.

Nico

**Comment by rcampbel3** [comment]
well, a few things... - the docs don't mention this, and the shortcut provides an error message that says, "you can allow this in settings, but the settings under 'privacy' only show a 'location' option. Exactly how would one alllow access to schedule in settings?

**Comment by verisgit** [comment]
It's not something you set in the privacy settings. It's in the shortcut setting at the top. Either way I deleted all that code out of the shortcut location, calendar, etc. there was a lot of stuff in there using things that aren't mentioned in the doco.

It would be great if we had the option to turn all this off during setup and choose what we share with Microsoft as people do have privacy concerns with the data.

Thanks

**Comment by nicolodiamante** [comment]
Thank you for bringing your concerns about sensitive data to my attention. I will try to add a setting that will allow the user to toggle calendar settings and any other sensitive information when configuring the shortcut. Additionally, I'll include details in the README regarding which sensitive data the shortcut will ask to use. 

Let me know if you have any other suggestions to improve the shortcut they are always welcome!

**Comment by verisgit** [comment]
Thanks for following it up.

**Comment by rcampbel3** [comment]
I'm still not clear how to enable calendar access for the shortcut in the 'shortcut setting at the top'

**Comment by nicolodiamante** [comment]
Hey everyone!

I just released an upgrade to SiriGPT, following your suggestion, to improve user privacy when setting up the shortcut. Now, you can decide if the shortcut can use your current location and access your calendar.

In response to @rcampbel3 , the upgraded version includes a new feature. If you use the word "schedule" when writing a prompt (e.g. What is my schedule for tomorrow?), you should get a summary of upcoming calendar events and reminders. Please note that this feature is currently in beta.

I have also added more features to give you more control over how to personalise SiriGPT. For more information, please check out the [README](https://github.com/nicolodiamante/SiriGPT/blob/main/README.md).

If you'd like to download the upgraded version you can do so by clicking the link [here](https://www.icloud.com/shortcuts/694c2e45a68f4839a8ae8c0058959d69) or downloading it from the README. 

I hope this version comes close to the idea you had in mind.

**Comment by nicolodiamante** [comment]
Hey everyone!

I just released an upgrade to SiriGPT, following your suggestion, to improve user privacy when setting up the shortcut. Now, you can decide if the shortcut can use your current location and access your calendar.

In response to @rcampbel3 , the upgraded version includes a new feature. If you use the word "schedule" when writing a prompt (e.g. What is my schedule for tomorrow?), you should get a summary of upcoming calendar events and reminders. Please note that this feature is currently in beta.

I have also added more features to give you more control over how to personalise SiriGPT. For more information, please check out the [README](https://github.com/nicolodiamante/SiriGPT/blob/main/README.md).

If you'd like to download the upgraded version you can do so by clicking the link [here](https://www.icloud.com/shortcuts/fa31a1a4b9f64be3bff0940043aeb382) or downloading it from the README. 

I hope this version comes close to the idea you had in mind.

**Comment by davidwu503** [comment]
The "What is my schedule for today?" works for me just one time. So great work as it is getting there. 

By the way when setting up and asking me for any prompts, I typed exactly the above. I thought I'd say that in case I'm doing anything wrong. Keep up the great work! I know how long these things take and the amount of work involved.
