### ISSUE TITLE
Using siri doesn't work

### ISSUE THREAD

**Issue by mrshappy0** [nicolodiamante/SiriGPT#7]
When I use the text prompt everything works fine. When I try and use voice-to-text with siri, it fails. It is setup to use Datajar to retreive my openAI api key. My usage is not at the limit, and I have a paid plus account. Well below my usage infact. 

It appears to keep failing the prompt with error "runner failed" which is too vague to debug. Any ideas? Not very familiar with Apple shorcuts so challenging for me to debug this.

**Comment by mrshappy0** [comment]
So I just tried again  (10th attempt or more) and waited for shortcuts to give me a notification. It resulted in this

Click on the error notification ==> Takes you to the line failed in the shortcut and shows red text with the associated error (error: The action couldn't run because the runner quit unexpectedly.) See photo for reference
![File](https://github.com/nicolodiamante/SiriGPT/assets/51244673/cac32d9f-dd6f-41f0-8243-f9a7e98715b1)

**Comment by nicolodiamante** [comment]
Hi Adam,
It seems that the issue might be related to your device's internet connection. Please, make sure you have access to a reliable Wi-Fi or cellular signal to ensure Siri works properly. Keep in mind that Siri needs to send data to Apple's servers, so an error between your device and the server could result in the inability of Siri to work. Additionally, the overloads on the OpenAI servers can also cause malfunctions. 

I have released an updated version of the shortcut. You can download it by clicking [here](https://www.icloud.com/shortcuts/694c2e45a68f4839a8ae8c0058959d69). 

If the issue persists, even with the upgraded version, try these steps:
1. Restart your iPhone
2. Check if "Listen for Hey Siri" is enabled
3. Reset Siri to recognize your voice
4. Make sure the microphone functions correctly

If after these steps the problem persists, you can try deleting Siri and the Dictionary History from the Settings menu. Go to Settings <a href="#"><img src="https://github.com/nicolodiamante/SiriGPT/assets/48920263/6256c23b-689b-4ee9-8986-f8399fde573f" draggable="false" ondragstart="return false;" alt="Arrow" title="Arrow" width="5.4px" /></a> Siri & Search <a href="#"><img src="https://github.com/nicolodiamante/SiriGPT/assets/48920263/6256c23b-689b-4ee9-8986-f8399fde573f" draggable="false" ondragstart="return false;" alt="Arrow" title="Arrow" width="5.4px" /></a> Siri & Dictionary History <a href="#"><img src="https://github.com/nicolodiamante/SiriGPT/assets/48920263/6256c23b-689b-4ee9-8986-f8399fde573f" draggable="false" ondragstart="return false;" alt="Arrow" title="Arrow" width="5.4px" /></a> Delete Siri & Dictionary History.

Please, let me know if this resolves the issue.

**Comment by nicolodiamante** [comment]
Hi Adam,
It seems that the issue might be related to your device's internet connection. Please, make sure you have access to a reliable Wi-Fi or cellular signal to ensure Siri works properly. Keep in mind that Siri needs to send data to Apple's servers, so an error between your device and the server could result in the inability of Siri to work. Additionally, the overloads on the OpenAI servers can also cause malfunctions. 

I have released an updated version of the shortcut. You can download it by clicking [here](https://www.icloud.com/shortcuts/fa31a1a4b9f64be3bff0940043aeb382). 

If the issue persists, even with the upgraded version, try these steps:
1. Restart your iPhone
2. Check if "Listen for Hey Siri" is enabled
3. Reset Siri to recognize your voice
4. Make sure the microphone functions correctly

If after these steps the problem persists, you can try deleting Siri and the Dictionary History from the Settings menu. Go to Settings <a href="#"><img src="https://github.com/nicolodiamante/SiriGPT/assets/48920263/6256c23b-689b-4ee9-8986-f8399fde573f" draggable="false" ondragstart="return false;" alt="Arrow" title="Arrow" width="5.4px" /></a> Siri & Search <a href="#"><img src="https://github.com/nicolodiamante/SiriGPT/assets/48920263/6256c23b-689b-4ee9-8986-f8399fde573f" draggable="false" ondragstart="return false;" alt="Arrow" title="Arrow" width="5.4px" /></a> Siri & Dictionary History <a href="#"><img src="https://github.com/nicolodiamante/SiriGPT/assets/48920263/6256c23b-689b-4ee9-8986-f8399fde573f" draggable="false" ondragstart="return false;" alt="Arrow" title="Arrow" width="5.4px" /></a> Delete Siri & Dictionary History.

Please, let me know if this resolves the issue.

**Comment by nicolodiamante** [comment]
Hello Adam,

I have released a new update (version 1.3.6). If there's a chance you've downloaded it already, could you kindly let me know if everything is operating smoothly, or if you've encountered any issues? I truly value your feedback. 

Thank you!
