### ISSUE TITLE
Regular expression was invalid. The value "'" is invalid.

### ISSUE THREAD

**Issue by aodrasa** [nicolodiamante/SiriGPT#8]
Getting the following error when running the shortcut, any ideas? 

![image](https://github.com/nicolodiamante/SiriGPT/assets/121209163/97db9a06-c031-45de-a089-249c00c3bfb9)

**Comment by nicolodiamante** [comment]
Hi,
Can you please provide more detail about when this problem occurs? Does it happen when you first launch the shortcut, or at a specific point after it has been launched?

**Comment by Harsha9554** [comment]
i face the same issue too. yeah i face it when i ran the shortcut for the first time

i'm not using paid version of chatgpt btw. i don't know if this only works for paid versions.

**Comment by nicolodiamante** [comment]
I understand you are both encountering the issue immediately when you run the shortcut. I'm going to look into it, the only possible causes I can think of right now could be your internet speed or Open AI server overloads. Could you please provide more information about when the issue occurred?

**Comment by imkarthi7** [comment]
Hi, 
I am also getting an error while running the shortcut. 

Could Not Run Match Text. 
Regular expression was invalid. The value "" is invalid

**Comment by nicolodiamante** [comment]
Hi everyone,

I hope you're all doing well! I wanted to let you know that I just released a new update (version 1.3.6). If any of you have already downloaded it, I would really appreciate your feedback. It would be great to know if you've encountered any problems or if everything is working smoothly for you. 

Thank you so much for your support!

**Comment by imkarthi7** [comment]
[image: WhatsApp Image 2023-07-19 at 22.53.26.jpg]

[image: WhatsApp Image 2023-07-19 at 22.53.07.jpg]

I am still getting the same error.

Thank you so much for creating such a shortcut (I haven't used it, but I
have heard good reviews about it).
It would be helpful if you could rectify the error.

Thanks
Karthik

**Comment by nicolodiamante** [comment]
Hi @imkarthi7 

I hope you're doing well. I'm sorry to hear that you're still experiencing problems. Could you please clarify if you are still encountering the same issue with the new version (version 1.3.6)? I want to ensure that I fully understand the problem you're facing. 

Additionally, it would be helpful if you could let me know if the error occurs immediately when you open or run the shortcut, or if it happens when you perform a specific task or request a certain action. This information will assist me in finding a solution for you. 

Lastly, if it's not too much trouble, could you please attach the images you sent in your previous message again? I apologise for the inconvenience, but I'm unable to visualise them at the moment.

Thank you,
Nico

**Comment by imkarthi7** [comment]
Hi,
Thank you for taking the time to reply.
I am attaching the screenshots. I have taken a screen recording. I've also
included the link for the screen recording.
Again thank you for making this shortcut.

For language preference can we add English (India) ?



https://drive.google.com/file/d/1TfNV0qN1DMJcX1NoDUG6x1pRuxDwDt1I/view?usp=sharing

**Comment by nicolodiamante** [comment]
Thank you for sharing the video. I have downloaded it and will carefully analyse it to determine the cause of the error. 

In regards to the implementation of English (India), I understand that there are some differences compared to standard English. To ensure the utmost accuracy in our translations, could you kindly provide some information regarding how much the sentence structures differ? This would greatly assist me in my efforts.

Furthermore, I was wondering if you could recommend a reliable website for translating sentences into English (India). Alternatively, if there is someone who could assist me in correcting sentences to the appropriate format, I would be incredibly grateful.

Thank you once again. I hope to resolve the issue.

**Comment by imkarthi7** [comment]
There are some differences in terms of vocabulary and grammar between US
and Indian English.
I've added a link to a website where it shows the difference between some
words in both languages. The website is not entirely correct, some of the
words used in US English are now commonly used here.
I think there is a change in spelling for some words. We use "color" and
"colour", nowadays.

I'll check for any websites which would help in understanding both
dialects.

While using ChatGPT we are getting replies in English(US), which so far was
the same to the English used here. There maybe some minute difference
between the two.

Anyways I'll definitely check for any major change in both languages.

Thanks
Karthik

**Comment by imkarthi7** [comment]
https://www.immihelp.com/indian-english-american-english-language-dictionary/

Forgot to include the link

**Comment by nicolodiamante** [comment]
If you wouldn't mind, I think the most efficient and quickest approach would be for me to share the exact sentences I used in the shortcut. Your assistance as a native speaker in appropriately translating them would be immensely helpful. By working together, we can easily add English (India) to the mix. Please let me know if you can lend a hand—I would truly appreciate it.

**Comment by imkarthi7** [comment]
Yes sure.
I would convert the sentences in the shortcut if it requires any changes.

**Comment by nicolodiamante** [comment]
Thank you so much for your assistance. I truly appreciate it. I will gladly provide you with the sentences for review, so you can take a look and make any necessary changes if needed. Your help is invaluable.

**Comment by nicolodiamante** [comment]
Hello, @imkarthi7. I have shared a link below which contains a series of sentences that require an adaptation into English (India). I have also provided translations in Hindi, assuming that it's your native language as I'm uncertain of your specific regional language. Please if Hindi is your mother tongue, could ensure that the sentences are correct? 

[SiriGPT Sentences](https://docs.google.com/spreadsheets/d/1HhL58-ncdNHlwWhoD2KiD6xfTFjdQXLyyAPXGw23huY/edit?usp=sharing)

I wanted to extend my gratitude once again for your invaluable assistance.
Nico

**Comment by imkarthi7** [comment]
Hi,
Most of the sentences are grammatically correct in terms of Indian English.
I have added or edited some of the sentences to commonly used language. It
is not necessary to include those as sentences in US English can be easily
understood.

I would be happy to help in case you need any.

Are you okay with sharing any of your socials?

Thanks
Karthik

**Comment by nicolodiamante** [comment]
Hi @imkarthi7 

I hope you are fine! I appreciate your willingness to continue to assist and the assistance you have provided thus far has certainly helped me.

In response to your question, I'd be happy to share my social media.

I released an updated version of SiriGPT (v1.4) if you want to try it, you can download it [here](https://www.icloud.com/shortcuts/8a0da1efb0364794aa5b51c50cc7aef0) or on the code page. It would be of great help if you could tell me if you are having the same problem or if it has been successfully resolved.

I look forward to hearing from you.

Nico

**Comment by imkarthi7** [comment]
Hey,
Thanks, Now it's working fine.
Is it okay if I allow it to share location and calendar data? Each time I'm
giving "allow once"

My API usage got exhausted so had to create a new account, that's why the
reply got delayed.
If possible share your LinkedIn/Twitter/Instagram, it would be great to
connect with you.

Thanks
Karthik

**Comment by nicolodiamante** [comment]
Hi Karthik,

I'm glad to hear that everything is working fine now. Yes, you can allow SiriGPT to share your location and calendar data if you feel comfortable with it. This way, you won't have to give permission each time.

I appreciate your willingness to connect. You can find me here: <a href="https://www.instagram.com/nicolodiamante/" alt="Nicol&#242; Diamante Instagram" title="Nicol&#242; Diamante Instagram">Instagram</a> & <a href="https://www.linkedin.com/in/nicolodiamante/" alt="Nicol&#242; Diamante LinkedIn" title="Nicol&#242; Diamante LinkedIn">LinkedIn</a>

Feel free to reach out if you have any more questions or need further assistance.

Nico
